### ISSUE TITLE
Parallel Execution reporting

### ISSUE THREAD

**Issue by saikrishna321** [email2vimalraj/CucumberExtentReporter#1]
@email2vimalraj i'm working on framework which will trigger feature files in parallel across android/ios devices. 

In this case when you have test running in parallel how does it work ?

**Comment by saikrishna321** [comment]
@email2vimalraj  i have some stuff done for running tests in parallel 

https://github.com/saikrishna321/CucumberExtentReporter

i see the report broken -- to run from commandline mvn clean -Dtest=Runnercukes test

**Comment by saikrishna321** [comment]
@email2vimalraj i have fixed it now.. give it a try

**Comment by email2vimalraj** [comment]
@saikrishna321 : I'll have a look and get back to you

**Comment by email2vimalraj** [comment]
@saikrishna321 : Finally I got a chance to read through your code. But I fear that I understood completely.

Few questions:
1. How do I include the ExtentCucumberFormatter as a plugin? I don't see any test for this.
2. It seems you are using JDK8. It would be great if you can use JDK7 style, since many of the users wouldn't have migrated to JDK8 yet.

Thanks.

**Comment by email2vimalraj** [comment]
@saikrishna321 : Any updates?

**Comment by saikrishna321** [comment]
@email2vimalraj i will re-work on it today and send u a PR

**Comment by email2vimalraj** [comment]
Thanks.

**Comment by hemanthsridhar** [comment]
hi @email2vimalraj any update on this?

**Comment by email2vimalraj** [comment]
No updates yet

**Comment by email2vimalraj** [comment]
The plugin is thread safe now from the release v2.0.0. Kindly give a try and let me know your findings.

Re-open in case issue persists.
