### ISSUE TITLE
Nll Pointer Exception - via build.gradle file

### ISSUE THREAD

**Issue by rupalJ** [email2vimalraj/CucumberExtentReporter#19]
Hi Vimal,

I have a java/cucumber/gradle project setup where I am setting  my cucumber configurations and plugins from the build.gradle file.

When I try to add the plugin within my build.gradle file then I am getting a null pointer exception; However when I execute my cucumber files outside the build.gradle file (i.e how you have done your setup in your example) then the reports work fine.

can you please help me how i can use this plugin via my build.gradle file?

**Comment by SluisM1** [comment]
Hi,


Not sure but it might be related to an issue I had before.


If you use your own cucumber commandline to kick of the feature files (instead Cucumber runner class see [1]). Then you will run into the NPE because not extent is being set. This is caused by a combination of the ExtentCucumberFormatter having 2 constuctor and Cucumber itself using the first one that matches.


For the CucumberExtentReporter this results in Cucumber using the default constructor instead of one with the File argument.


This all cause the cucumber commandline with the following argument to result in the NPE.


    --plugin com.cucumber.listener.ExtentCucumberFormatter: <your output file>


I fixed this in my own project by wrapping the cucumber CLI Main method in my own and CLI Main method and call one of the static initiateExtentCucumberFormatter methods.


This is not best fix, but helped me to proceed without upstream changes. I can see 2 solutions to fix this:

1) Change the order in which Cucumber looks for constructor. Default constructor should be last instead of first.

2) Fix ExtentCucumberFormatter to remove the default constructor and have all static initiateExtentCucumberFormatter use the existing/old File arg constructor.


Hope this helps.


Regards,


Misl


[1] https://github.com/email2vimalraj/CucumberExtentReporter



________________________________

**Comment by email2vimalraj** [comment]
Interesting, never executed tests through Cucumber CLI. Let me try and comment back.

**Comment by SluisM1** [comment]
Some additional info:


Have a look at Cucumber-jvm class PluginFactory at


https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/formatter/PluginFactory.java


On line 50 you can see CTOR_ARGS being defined with the order in which Formatter constructors are being searched for. Null (no-arg) first and File.class last. These are actually the 2 constructors present in ExtentCucumberFormatter.


On line 96  the actual search for the contructor using the CTOR_ARGS order. The first one found (in our case the no-arg constructor) is being used. Which as stated in my previous email results in a NPE since no extent is being created.


Regards,


Minto


________________________________

**Comment by chOOnz** [comment]
I ran into the same issue yesterday. Is there a workaround for this?

**Comment by email2vimalraj** [comment]
@chOOnz : Are you facing this issue when using gradle or CLI?

**Comment by chOOnz** [comment]
@email2vimalraj I'm facing the issue when using my custom gradle plugin with a custom task which executes cucumber via the commandline. I just add `--plugin com.cucumber.listener.ExtentCucumberFormatter` as argument for cucumber and at this point I get the NPE.

**Comment by misl** [comment]
My workaround is/was overload the cucumber CLI with my own CLI. I used the following code:

```
public final class TestAutomation {

    // ------------------------------------------------------------------------
    // Constants
    // ------------------------------------------------------------------------

    private static final Pattern PATTERN_PLUGIN_DETECT = Pattern.compile("com.cucumber.listener.ExtentCucumberFormatter:(.*)");

    private static final String OPTION_PLUGIN = "--plugin";

    // ------------------------------------------------------------------------
    // Entry point
    // ------------------------------------------------------------------------

    public static void main(final String[] argv) throws Throwable {
        // Properly initialize ExtentCucumberFormatter
        final String extendFormatterArg = getExtentCucumberFormatterArg(Arrays.asList(argv));
        if (extendFormatterArg != null) {
            if (extendFormatterArg.isEmpty()) {
                ExtentCucumberFormatter.initiateExtentCucumberFormatter();
            } else {
                ExtentCucumberFormatter.initiateExtentCucumberFormatter(new File(extendFormatterArg));
            }
        }

        // Pass on to cucumber's own cli.
        Main.main(argv);
    }

    // ------------------------------------------------------------------------
    // Private methods
    // ------------------------------------------------------------------------

    private static String getExtentCucumberFormatterArg(final List<String> args) {
        boolean pluginArgument = false;
        for (final String arg : args) {
            if (OPTION_PLUGIN.equalsIgnoreCase(arg)) {
                pluginArgument = true;
                continue;
            }
            if (pluginArgument) {
                final Matcher matcher = PATTERN_PLUGIN_DETECT.matcher(arg);

                if (matcher.matches()) {
                    return matcher.group(1).trim();
                }
            }
            pluginArgument = false;
        }
        return null;
    }
}
```

**Comment by chOOnz** [comment]
@misl Thanks for sharing this! I will try it out tomorrow.

**Comment by chOOnz** [comment]
@misl Works like a charm. Thanks!

**Comment by misl** [comment]
Happy I could help :-)

**Comment by email2vimalraj** [comment]
Thanks @misl for helping the community. Appreciate your effort.

**Comment by SluisM1** [comment]
Glad I could be of help :-)

_________________________________________________________________________________

This email (including any attachments to it) is confidential, legally privileged, subject to copyright and is sent for the personal attention of the intended recipient only. If you have received this email in error, please advise us immediately and delete it. You are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Although we have taken reasonable precautions to ensure no viruses are present in this email, we cannot accept responsibility for any loss or damage arising from the viruses in this email or attachments. We exclude any liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided in this email or its attachments, unless that information is subsequently confirmed in writing. 
_________________________________________________________________________________
