### ISSUE TITLE
Report showing wrong test counts

### ISSUE THREAD

**Issue by JaspalAujla** [email2vimalraj/CucumberExtentReporter#38]
In my test suite, I have 2 test scenarios. 1 scenario have 3 tests with different set of data. So, the total count of tests are 4. But, the report is reflecting 16, which is equal to test steps.

![cucumberextent](https://cloud.githubusercontent.com/assets/17103120/24532819/dee27546-161f-11e7-9895-e1ea6517a0c0.PNG)

**Comment by anshooarora** [comment]
This is because you are not creating a bdd style report.

**Comment by email2vimalraj** [comment]
@anshooarora : yes you are right, this plugin is not by default creates the BDD style report. Because the extent report is still doesn't have the implementation for the `Scenario Outline`.

I'm working on to add the `Scenario Outline` and make this plugin BDD friendly.

@JaspalAujla : Thanks for highlighting this.

**Comment by email2vimalraj** [comment]
Update to the latest version 3.0.0
