### ISSUE TITLE
Unable to view screenshot in report.html

### ISSUE THREAD

**Issue by sairashabnam** [email2vimalraj/CucumberExtentReporter#48]
Hi Vimal,

I have attached my code for your review.I am unable to view screenshots attached in the report.Please help me in resolving this.

[https://www.dropbox.com/s/fup61tjnzxzhm2z/CucumberExtentReport.zip?dl=0](url)

**Comment by email2vimalraj** [comment]
@sairashabnam : Difficult for me to go through each and every part of your code. It would be helpful if you can post the snippet which causes the issue. Also, try updating to the latest released version 3.0.0 and see if the issue still persists.

**Comment by SyedSairaSabanam** [comment]
Hi Vimal,

![cucumberreport](https://user-images.githubusercontent.com/29270190/28776724-787fec56-7615-11e7-8fce-cbaa82ebbc3e.PNG)
![cucumberreport1](https://user-images.githubusercontent.com/29270190/28776723-787d7d5e-7615-11e7-8fa2-c2c12a5975fc.PNG)
As you can see in my report I have got screenshot in the third step as a link.When I click on the link am able to see the screenshot.
Is it possible to attach screenshot below the step instead of a link?

Regards,
Saira

**Comment by email2vimalraj** [comment]
Hi Saira,

That is the default behavior of Extent report. Kindly raise this issue in extent report repo.

Thanks
Vimalraj
