### ISSUE TITLE
Adding byte[] or base64 to the report.

### ISSUE THREAD

**Issue by sakthy1127** [email2vimalraj/CucumberExtentReporter#51]
Hi vimalraj,
This report helps me a lot to show a end report to the customer and you did a great job by creating this for cucumber. I don't want to put this as an issue, but want to give a suggestion that if there is option  to add screenshot as byte[] or base64 format it would be very helpful to send a report to the client (with less size). As the image is take more size of the report. Instead of adding image path to the report, option is provided to add image as byte[] format or base64 format in the report then it would be great.

Thanks
Sakthy

**Comment by email2vimalraj** [comment]
@sakthy1127 : I would be happy to add this feature if extent report natively supports this. I don't think it does.

Your understanding on `base64` is wrong. Your report file size will be atleast 2 times bigger if you start adding base64 format. Earlier, the extent report had a support for `base64` and removed because of this issue.
