### ISSUE TITLE
ExtentReport does not show whole error message for AssertJ condition 

### ISSUE THREAD

**Issue by mikiwys** [email2vimalraj/CucumberExtentReporter#6]
Hi,

I am using in my project:
```
		<dependency>
			<groupId>com.vimalselvam</groupId>
			<artifactId>cucumber-extentsreport</artifactId>
			<version>1.0.0</version>
		</dependency>
```

In cucumber step definition I put _Assertj_ condition. _ExtentReport_ does not show whole error message.

Feature file:

```
Feature: Sample
  Scenario: Test
    Given create
```

Step definition:

```
@Given("^create")
public void create() throws Throwable {
  assertThat("not empty string").is(new Condition<String>(String::isEmpty, "empty"));
}
```

Error in console:

```
java.lang.AssertionError: 
Expecting:
 <"not empty string">
to be <empty>
	at com.package.StepDefinitions.create(StepDefinitions.java:38)
	at ✽.Given create(Sample.feature:3)
```

Details visible in ExtentReports:

```
java.lang.AssertionError: Expecting: <"not empty string"> to be at com.package.StepDefinitions.create(StepDefinitions.java:38) at ✽.Given create(Sample.feature:3)
```

The text `<empty>` is missing above.

**Comment by email2vimalraj** [comment]
This seems to be a bug in ExtentReport itself. Because it considers the <empty> as an html tag.

Refer the inspected screenshot:

<img width="989" alt="screen shot 2016-05-22 at 8 22 19 pm" src="https://cloud.githubusercontent.com/assets/1214686/15454588/fa45ac74-205a-11e6-9817-061e9501c82c.png">

Kindly report it to: https://github.com/anshooarora/extentreports/issues/
